language: java

jdk:
  - oraclejdk8

sudo: required

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

services:
    - docker

notifications:
  email: false
  slack: tandil:2a0bvGqxPuOtbyJZadge1w4z

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker build -t szulianiheld/librarian-bot .;
    docker push szulianiheld/librarian-bot;
    fi
