application:
  version: 1.0.0-SNAPSHOT

endpoints:
    health:
        sensitive: false

management:
    security:
        enabled: false

logging:
    level:
        org:
            maiabot:
                librarianbot: TRACE

spring:
    messages:
        basename: i18n/messages
    h2:
      console:
        enabled: true
        path: /h2-console
    datasource:
      url: jdbc:h2:file:~/h2/librarianDB
      username: librarian
      password:
      driverClassName: org.h2.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true

# JBot
rtmUrl: https://slack.com/api/rtm.start?token={token}&simple_latest&no_unreads
slackBotToken: xoxb-153343187078-76qbrTsBEI5soXMnVp8Q0n7p