-- TABLE: book
CREATE TABLE IF NOT EXISTS book (
  id INTEGER NOT NULL AUTO_INCREMENT,
  name VARCHAR (100) NOT NULL,
  author VARCHAR (100) NOT NULL,
  date TIMESTAMP NOT NULL,
  description VARCHAR (255) NOT NULL,
  editorial VARCHAR (100) NOT NULL,
  imprint VARCHAR (100) NOT NULL,
  is_digital BOOLEAN NOT NULL,
  isbn13 VARCHAR (13) NOT NULL,
  url VARCHAR (255) NOT NULL,
  PRIMARY KEY (id)
);

-- TABLE: User
CREATE TABLE IF NOT EXISTS user (
	id INTEGER NOT NULL AUTO_INCREMENT,
	is_admin BOOLEAN NOT NULL,
	name VARCHAR (50) NOT NULL,
	surname VARCHAR (70) NOT NULL,
	user_name VARCHAR (70) NOT NULL UNIQUE,
  PRIMARY KEY (id)
);



